// Comprehensive packages database for search and filtering
export const packagesData = [
  // Kashmir Tour Packages
  {
    id: 1,
    name: "Glimpse of Kashmir Tour",
    nights: 3,
    days: 4,
    category: "Kashmir Tour",
    price: 10999,
    originalPrice: 13999,
    discount: 21,
    locations: ["Srinagar", "Pahalgam", "Gulmarg"],
    activities: ["Sightseeing", "Shikara Ride", "Garden Visits"],
    link: "/packages/3-nights-4-days-srinagar-pahalgam-gulmarg-tour",
    rating: 4.5,
    reviews: 234,
    bestFor: "Couples",
    season: "All Season",
    highlights: ["Dal Lake Shikara Ride", "Mughal Gardens", "Gulmarg Gondola"],
    includes: ["Accommodation", "Breakfast", "Transfers", "Sightseeing"],
    difficulty: "Easy",
    groupSize: "2-15 people",
    cancellation: "Free cancellation up to 24 hours",
    image: "/assets/kashmir-tour-package.jpg",
    featured: true
  },
  {
    id: 2,
    name: "Kashmir Family Tour",
    nights: 5,
    days: 6,
    category: "Family",
    price: 11999,
    originalPrice: 15999,
    discount: 25,
    locations: ["Srinagar", "Pahalgam", "Gulmarg"],
    activities: ["Family Activities", "Sightseeing", "Pony Rides"],
    link: "/packages/kashmir-family-tour",
    rating: 4.7,
    reviews: 189,
    bestFor: "Families",
    season: "Summer",
    highlights: ["Family-friendly accommodations", "Kid-safe activities", "Local culture experience"],
    includes: ["Family rooms", "All meals", "Transportation", "Guide"],
    difficulty: "Easy",
    groupSize: "4-20 people",
    cancellation: "Free cancellation up to 48 hours",
    image: "/assets/family-tour.jpg",
    featured: false
  },
  {
    id: 3,
    name: "Kashmir Honeymoon Tour",
    nights: 3,
    days: 4,
    category: "Honeymoon",
    price: 13999,
    originalPrice: 17999,
    discount: 22,
    locations: ["Srinagar", "Pahalgam"],
    activities: ["Romantic Dinner", "Shikara Ride", "Garden Walks"],
    link: "/packages/kashmir-honeymoon-tour",
    rating: 4.8,
    reviews: 312,
    bestFor: "Couples",
    season: "All Season",
    highlights: ["Candlelight dinner", "Flower bed decoration", "Couple photography"],
    includes: ["Romantic accommodation", "Special meals", "Private transfers"],
    difficulty: "Easy",
    groupSize: "2 people",
    cancellation: "Free cancellation up to 24 hours",
    image: "/assets/honeymoon-tour.jpg",
    featured: true
  },
  {
    id: 4,
    name: "Kashmir Gulmarg Tour",
    nights: 3,
    days: 4,
    category: "Adventure",
    price: 10999,
    originalPrice: 13999,
    discount: 21,
    locations: ["Gulmarg", "Srinagar"],
    activities: ["Skiing", "Gondola Ride", "Snow Activities"],
    link: "/packages/kashmir-gulmarg-tour",
    rating: 4.6,
    reviews: 156,
    bestFor: "Adventure Seekers",
    season: "Winter",
    highlights: ["Gulmarg Gondola", "Skiing lessons", "Snow activities"],
    includes: ["Mountain accommodation", "Equipment rental", "Instructor"],
    difficulty: "Medium",
    groupSize: "2-12 people",
    cancellation: "Weather dependent cancellation",
    image: "/assets/gulmarg-tour.jpg",
    featured: false
  },
  {
    id: 5,
    name: "Kashmir Houseboat Tour",
    nights: 3,
    days: 4,
    category: "Luxury",
    price: 8999,
    originalPrice: 11999,
    discount: 25,
    locations: ["Srinagar"],
    activities: ["Houseboat Stay", "Dal Lake", "Floating Gardens"],
    link: "/packages/kashmir-houseboat-tour",
    rating: 4.4,
    reviews: 98,
    bestFor: "Couples",
    season: "Summer",
    highlights: ["Traditional houseboat", "Lake views", "Floating market visit"],
    includes: ["Houseboat accommodation", "Kashmiri meals", "Shikara rides"],
    difficulty: "Easy",
    groupSize: "2-6 people",
    cancellation: "Free cancellation up to 24 hours",
    image: "/assets/houseboat-tour.jpg",
    featured: true
  },
  {
    id: 6,
    name: "Kashmir Package with Patnitop",
    nights: 8,
    days: 9,
    category: "Extended",
    price: 21999,
    originalPrice: 29999,
    discount: 27,
    locations: ["Srinagar", "Pahalgam", "Gulmarg", "Patnitop"],
    activities: ["Hill Station", "Sightseeing", "Nature Walks"],
    link: "/packages/kashmir-package-with-patnitop",
    rating: 4.5,
    reviews: 87,
    bestFor: "Families",
    season: "Summer",
    highlights: ["Complete Kashmir tour", "Hill station experience", "Extended itinerary"],
    includes: ["Premium hotels", "All transfers", "Guided tours"],
    difficulty: "Easy",
    groupSize: "2-15 people",
    cancellation: "Free cancellation up to 72 hours",
    image: "/assets/patnitop-tour.jpg",
    featured: false
  },

  // Honeymoon Special Packages
  {
    id: 7,
    name: "Magical Kashmir Honeymoon",
    nights: 4,
    days: 5,
    category: "Honeymoon",
    price: 15999,
    originalPrice: 19999,
    discount: 20,
    locations: ["Srinagar", "Pahalgam", "Gulmarg"],
    activities: ["Romantic Experiences", "Houseboat", "Candlelight Dinner"],
    link: "/packages/honeymoon-magical-kashmir-tour",
    rating: 4.8,
    reviews: 256,
    bestFor: "Couples",
    season: "Summer",
    highlights: ["Houseboat night", "Romantic setup", "Private dining"],
    includes: ["Luxury accommodation", "Couple activities", "Special arrangements"],
    difficulty: "Easy",
    groupSize: "2 people",
    cancellation: "Free cancellation up to 24 hours",
    image: "/assets/magical-honeymoon.jpg",
    featured: true
  },
  {
    id: 8,
    name: "Best Selling Kashmir Tour",
    nights: 5,
    days: 6,
    category: "Bestseller",
    price: 19999,
    originalPrice: 24999,
    discount: 20,
    locations: ["Srinagar", "Pahalgam", "Gulmarg"],
    activities: ["Complete Package", "Adventure", "Cultural Experience"],
    link: "/packages/best-selling-kashmir-tour",
    rating: 4.9,
    reviews: 445,
    bestFor: "All",
    season: "Summer",
    highlights: ["Most popular package", "Value for money", "Comprehensive tour"],
    includes: ["Premium hotels", "All activities", "Expert guide"],
    difficulty: "Easy",
    groupSize: "2-20 people",
    cancellation: "Free cancellation up to 48 hours",
    image: "/assets/bestseller-tour.jpg",
    featured: true
  },
  {
    id: 9,
    name: "Scenic Kashmir Tour",
    nights: 6,
    days: 7,
    category: "Photography",
    price: 23999,
    originalPrice: 29999,
    discount: 20,
    locations: ["Srinagar", "Pahalgam", "Gulmarg", "Sonamarg"],
    activities: ["Photography", "Scenic Views", "Sunrise Tours"],
    link: "/packages/scenic-kashmir-tour",
    rating: 4.7,
    reviews: 178,
    bestFor: "Photographers",
    season: "Summer",
    highlights: ["Photography guide", "Golden hour tours", "Scenic locations"],
    includes: ["Photography permits", "Early morning tours", "Professional guide"],
    difficulty: "Medium",
    groupSize: "2-12 people",
    cancellation: "Free cancellation up to 48 hours",
    image: "/assets/scenic-tour.jpg",
    featured: false
  },

  // Adventure & Winter Packages
  {
    id: 10,
    name: "Gulmarg Skiing Adventure",
    nights: 4,
    days: 5,
    category: "Adventure",
    price: 18999,
    originalPrice: 24999,
    discount: 24,
    locations: ["Gulmarg", "Srinagar"],
    activities: ["Skiing", "Snowboarding", "Snow Trekking"],
    link: "/packages/gulmarg-skiing-adventure",
    rating: 4.6,
    reviews: 134,
    bestFor: "Adventure Seekers",
    season: "Winter",
    highlights: ["Professional skiing lessons", "Equipment included", "Snow sports"],
    includes: ["Ski equipment", "Instructor", "Safety gear"],
    difficulty: "Hard",
    groupSize: "2-8 people",
    cancellation: "Weather dependent",
    image: "/assets/skiing-adventure.jpg",
    featured: false
  },
  {
    id: 11,
    name: "Winter Wonderland Kashmir",
    nights: 5,
    days: 6,
    category: "Adventure",
    price: 22999,
    originalPrice: 29999,
    discount: 23,
    locations: ["Gulmarg", "Pahalgam", "Srinagar"],
    activities: ["Snow Sports", "Winter Trekking", "Ice Activities"],
    link: "/packages/winter-wonderland-kashmir",
    rating: 4.5,
    reviews: 89,
    bestFor: "Adventure Seekers",
    season: "Winter",
    highlights: ["Snow experience", "Winter activities", "Cozy accommodations"],
    includes: ["Winter gear", "Heated accommodation", "Hot meals"],
    difficulty: "Medium",
    groupSize: "2-10 people",
    cancellation: "Weather dependent",
    image: "/assets/winter-wonderland.jpg",
    featured: false
  },

  // Cultural & Extended Tours
  {
    id: 12,
    name: "Gurez Valley Cultural Tour",
    nights: 4,
    days: 5,
    category: "Cultural",
    price: 16999,
    originalPrice: 21999,
    discount: 23,
    locations: ["Gurez Valley", "Srinagar"],
    activities: ["Cultural Experience", "Local Life", "Traditional Crafts"],
    link: "/packages/gurez-valley-cultural-tour",
    rating: 4.4,
    reviews: 67,
    bestFor: "Culture Enthusiasts",
    season: "Summer",
    highlights: ["Authentic cultural experience", "Local interaction", "Traditional meals"],
    includes: ["Cultural guide", "Traditional accommodation", "Local meals"],
    difficulty: "Medium",
    groupSize: "2-12 people",
    cancellation: "Free cancellation up to 48 hours",
    image: "/assets/gurez-cultural.jpg",
    featured: false
  },
  {
    id: 13,
    name: "Kashmir with Vaishno Devi",
    nights: 8,
    days: 9,
    category: "Pilgrimage",
    price: 20999,
    originalPrice: 26999,
    discount: 22,
    locations: ["Jammu", "Vaishno Devi", "Srinagar", "Pahalgam"],
    activities: ["Pilgrimage", "Temple Visit", "Spiritual Journey"],
    link: "/packages/kashmir-with-vaishno-devi",
    rating: 4.8,
    reviews: 298,
    bestFor: "Pilgrims",
    season: "All Season",
    highlights: ["Sacred pilgrimage", "Temple darshan", "Spiritual experience"],
    includes: ["Helicopter booking", "VIP darshan", "Religious guide"],
    difficulty: "Medium",
    groupSize: "2-25 people",
    cancellation: "Free cancellation up to 72 hours",
    image: "/assets/vaishno-devi.jpg",
    featured: true
  },

  // Luxury & Family Packages
  {
    id: 14,
    name: "Luxury Kashmir Experience",
    nights: 6,
    days: 7,
    category: "Luxury",
    price: 35999,
    originalPrice: 45999,
    discount: 22,
    locations: ["Srinagar", "Pahalgam", "Gulmarg"],
    activities: ["Luxury Experiences", "Private Tours", "Premium Services"],
    link: "/packages/luxury-kashmir-experience",
    rating: 4.9,
    reviews: 123,
    bestFor: "Luxury Travelers",
    season: "Summer",
    highlights: ["5-star accommodations", "Private guides", "Exclusive experiences"],
    includes: ["Luxury hotels", "Private transport", "Concierge service"],
    difficulty: "Easy",
    groupSize: "2-8 people",
    cancellation: "Free cancellation up to 24 hours",
    image: "/assets/luxury-experience.jpg",
    featured: true
  },
  {
    id: 15,
    name: "Kashmir Family Adventure",
    nights: 7,
    days: 8,
    category: "Family",
    price: 28999,
    originalPrice: 36999,
    discount: 22,
    locations: ["Srinagar", "Pahalgam", "Gulmarg", "Sonamarg"],
    activities: ["Family Activities", "Adventure Sports", "Educational Tours"],
    link: "/packages/kashmir-family-adventure",
    rating: 4.7,
    reviews: 156,
    bestFor: "Families",
    season: "Summer",
    highlights: ["Kid-friendly activities", "Educational tours", "Safety assured"],
    includes: ["Family accommodation", "Activity equipment", "Safety gear"],
    difficulty: "Easy",
    groupSize: "4-20 people",
    cancellation: "Free cancellation up to 48 hours",
    image: "/assets/family-adventure.jpg",
    featured: false
  },

  // Trekking & Nature Packages
  {
    id: 16,
    name: "Kashmir Trekking Expedition",
    nights: 8,
    days: 9,
    category: "Trekking",
    price: 24999,
    originalPrice: 32999,
    discount: 24,
    locations: ["Pahalgam", "Sonamarg", "Base Camps"],
    activities: ["Trekking", "Camping", "Nature Photography"],
    link: "/packages/kashmir-trekking-expedition",
    rating: 4.6,
    reviews: 87,
    bestFor: "Trekkers",
    season: "Summer",
    highlights: ["High altitude trekking", "Camping experience", "Nature immersion"],
    includes: ["Camping gear", "Trekking guide", "Safety equipment"],
    difficulty: "Hard",
    groupSize: "4-12 people",
    cancellation: "Weather dependent",
    image: "/assets/trekking-expedition.jpg",
    featured: false
  },

  // Short Weekend Packages
  {
    id: 17,
    name: "Weekend Kashmir Getaway",
    nights: 2,
    days: 3,
    category: "Weekend",
    price: 7999,
    originalPrice: 9999,
    discount: 20,
    locations: ["Srinagar"],
    activities: ["Quick Sightseeing", "Shikara Ride", "Garden Visit"],
    link: "/packages/weekend-kashmir-getaway",
    rating: 4.3,
    reviews: 167,
    bestFor: "Working Professionals",
    season: "All Season",
    highlights: ["Quick getaway", "Budget-friendly", "Essential experiences"],
    includes: ["Hotel stay", "Basic sightseeing", "Airport transfers"],
    difficulty: "Easy",
    groupSize: "2-8 people",
    cancellation: "Free cancellation up to 12 hours",
    image: "/assets/weekend-getaway.jpg",
    featured: false
  },
  {
    id: 18,
    name: "Extended Kashmir Valley Tour",
    nights: 10,
    days: 11,
    category: "Extended",
    price: 42999,
    originalPrice: 55999,
    discount: 23,
    locations: ["Srinagar", "Pahalgam", "Gulmarg", "Sonamarg", "Yusmarg", "Doodhpathri"],
    activities: ["Complete Valley Tour", "Off-beat Destinations", "Cultural Immersion"],
    link: "/packages/extended-kashmir-valley-tour",
    rating: 4.8,
    reviews: 78,
    bestFor: "Travel Enthusiasts",
    season: "Summer",
    highlights: ["Complete valley coverage", "Hidden gems", "Local experiences"],
    includes: ["Premium accommodation", "All destinations", "Expert guide"],
    difficulty: "Medium",
    groupSize: "2-15 people",
    cancellation: "Free cancellation up to 72 hours",
    image: "/assets/extended-valley.jpg",
    featured: true
  }
];

// Filter helper functions
export const getUniqueValues = (key) => {
  const values = packagesData.map(pkg => {
    if (key === 'locations') {
      return pkg[key];
    }
    return pkg[key];
  });
  
  if (key === 'locations') {
    return [...new Set(values.flat())].sort();
  }
  
  return [...new Set(values)].filter(Boolean).sort();
};

export const getPriceRanges = () => [
  'Under ₹10,000',
  '₹10,000-₹15,000', 
  '₹15,000-₹20,000',
  '₹20,000-₹30,000',
  'Above ₹30,000'
];

export const getDurationOptions = () => [
  '2-3 Days',
  '4-5 Days', 
  '6-7 Days',
  '8+ Days'
];

export const getRatingOptions = () => [
  '4.0+',
  '4.5+', 
  '4.7+'
];